/**
 * NCAA logo asset mapping — generated from assets/icons/NCAA Logos/*.png
 * Maps a normalized team key (lowercase, alphanumeric-only) to its logo filename.
 */

export const TEAM_NCAA_LOGOS: Record<string, string> = {
  abilenechristian: 'abileneChristian.png',
  airforce: 'airForce.png',
  akron: 'akron.png',
  alabama: 'alabama.png',
  alabamaam: 'alabamaAM.png',
  alabamastate: 'alabamaState.png',
  albany: 'albany.png',
  alcornstate: 'alcornState.png',
  appalachianstate: 'appalachianState.png',
  arizona: 'arizona.png',
  arizonastate: 'arizonaState.png',
  arkansas: 'arkansas.png',
  arkansaspinebluff: 'arkansasPineBluff.png',
  arkansasstate: 'arkansasState.png',
  army: 'army.png',
  auburn: 'auburn.png',
  austinpeay: 'austinPeay.png',
  ballstate: 'ballState.png',
  baylor: 'baylor.png',
  bethunecookman: 'bethuneCookman.png',
  boisestate: 'boiseState.png',
  boston: 'boston.png',
  bowlinggreen: 'bowlingGreen.png',
  brown: 'brown.png',
  bryant: 'bryant.png',
  bucknell: 'bucknell.png',
  buffalo: 'buffalo.png',
  butler: 'butler.png',
  byu: 'byu.png',
  california: 'california.png',
  calpoly: 'calPoly.png',
  campbell: 'campbell.png',
  centralarkansas: 'centralArkansas.png',
  centralconnecticut: 'centralConnecticut.png',
  centralmichigan: 'centralMichigan.png',
  charlestonsouthern: 'charlestonSouthern.png',
  charlotte: 'charlotte.png',
  chattanooga: 'chattanooga.png',
  cincinnati: 'cincinnati.png',
  citadel: 'citadel.png',
  clemson: 'clemson.png',
  coastalcarolina: 'coastalCarolina.png',
  colgate: 'colgate.png',
  colorado: 'colorado.png',
  coloradostate: 'coloradoState.png',
  columbia: 'columbia.png',
  connecticut: 'connecticut.png',
  cornell: 'cornell.png',
  dartmouth: 'dartmouth.png',
  davidson: 'davidson.png',
  dayton: 'dayton.png',
  delaware: 'delaware.png',
  delawarestate: 'delawareState.png',
  drake: 'drake.png',
  duke: 'duke.png',
  duquesne: 'duquesne.png',
  eastcarolina: 'eastCarolina.png',
  easternillinois: 'easternIllinois.png',
  easternkentucky: 'easternKentucky.png',
  easternmichigan: 'easternMichigan.png',
  easternwashington: 'easternWashington.png',
  easttennessee: 'eastTennessee.png',
  elon: 'elon.png',
  florida: 'florida.png',
  floridaam: 'floridaAM.png',
  floridaatlantic: 'floridaAtlantic.png',
  floridaintl: 'floridaIntl.png',
  floridastate: 'floridaState.png',
  fordham: 'fordham.png',
  fresnostate: 'fresnoState.png',
  furman: 'furman.png',
  gardnerwebb: 'gardnerWebb.png',
  georgetown: 'georgetown.png',
  georgia: 'georgia.png',
  georgiasouthern: 'georgiaSouthern.png',
  georgiastate: 'georgiaState.png',
  georgiatech: 'georgiaTech.png',
  gramblingstate: 'gramblingState.png',
  hampton: 'hampton.png',
  harvard: 'harvard.png',
  hawaii: 'hawaii.png',
  holycross: 'holyCross.png',
  houston: 'houston.png',
  houstonbaptist: 'houstonBaptist.png',
  howard: 'howard.png',
  idaho: 'idaho.png',
  idahostate: 'idahoState.png',
  illinois: 'illinois.png',
  illinoisstate: 'illinoisState.png',
  incarnateword: 'incarnateWord.png',
  indiana: 'indiana.png',
  indianastate: 'indianaState.png',
  iowa: 'iowa.png',
  iowastate: 'iowaState.png',
  jacksonstate: 'jacksonState.png',
  jacksonville: 'jacksonville.png',
  jacksonvillestate: 'jacksonvilleState.png',
  jamesmadison: 'jamesMadison.png',
  kansas: 'kansas.png',
  kansasstate: 'kansasState.png',
  kennesawstate: 'kennesawState.png',
  kentstate: 'kentState.png',
  kentucky: 'kentucky.png',
  lafayette: 'lafayette.png',
  lamar: 'lamar.png',
  lehigh: 'lehigh.png',
  liberty: 'liberty.png',
  louisianalafayette: 'louisianaLafayette.png',
  louisianamonroe: 'louisianaMonroe.png',
  louisianatech: 'LouisianaTech.png',
  louisville: 'louisville.png',
  lsu: 'lsu.png',
  maine: 'maine.png',
  marist: 'marist.png',
  marshall: 'marshall.png',
  maryland: 'maryland.png',
  massachusetts: 'massachusetts.png',
  mcneesestate: 'mcNeeseState.png',
  memphis: 'memphis.png',
  mercer: 'mercer.png',
  miami: 'miami.png',
  miamioh: 'miamiOH.png',
  michigan: 'michigan.png',
  michiganstate: 'michiganState.png',
  middletennessee: 'middleTennessee.png',
  minnesota: 'minnesota.png',
  mississippistate: 'mississippiState.png',
  mississippivalleystate: 'mississippiValleyState.png',
  missouri: 'missouri.png',
  missouristate: 'missouriState.png',
  monmouth: 'monmouth.png',
  montana: 'montana.png',
  montanastate: 'montanaState.png',
  moreheadstate: 'moreheadState.png',
  morganstate: 'morganState.png',
  murraystate: 'murrayState.png',
  navy: 'navy.png',
  ncstate: 'ncState.png',
  nebraska: 'nebraska.png',
  nevada: 'nevada.png',
  newhampshire: 'newHampshire.png',
  newmexico: 'newMexico.png',
  newmexicostate: 'newMexicoState.png',
  nichollsstate: 'nichollsState.png',
  norfolkstate: 'norfolkState.png',
  northcarolina: 'northCarolina.png',
  northcarolinaat: 'northCarolinaAT.png',
  northcarolinacentral: 'northCarolinaCentral.png',
  northdakota: 'northDakota.png',
  northdakotastate: 'northDakotaState.png',
  northernarizona: 'northernArizona.png',
  northerncolorado: 'northernColorado.png',
  northernillinois: 'northernIllinois.png',
  northerniowa: 'northernIowa.png',
  northtexas: 'northTexas.png',
  northwestern: 'northwestern.png',
  northwesternstate: 'northwesternState.png',
  notredame: 'notreDame.png',
  ohio: 'ohio.png',
  ohiostate: 'ohioState.png',
  oklahoma: 'oklahoma.png',
  oklahomastate: 'OklahomaState.png',
  olddominion: 'oldDominion.png',
  olemiss: 'oleMiss.png',
  oregon: 'oregon.png',
  oregonstate: 'oregonState.png',
  penn: 'penn.png',
  pennstate: 'pennState.png',
  pittsburgh: 'pittsburgh.png',
  portlandstate: 'portlandState.png',
  prairieview: 'prairieView.png',
  presbyteriancollege: 'presbyterianCollege.png',
  princeton: 'princeton.png',
  purdue: 'purdue.png',
  rhodeisland: 'rhodeIsland.png',
  rice: 'rice.png',
  richmond: 'richmond.png',
  robertmorris: 'robertMorris.png',
  rutgers: 'rutgers.png',
  sacramentostate: 'sacramentoState.png',
  sacredheart: 'sacredHeart.png',
  samford: 'samford.png',
  samhoustonstate: 'samHoustonState.png',
  sandiego: 'sanDiego.png',
  sandiegostate: 'sanDiegoState.png',
  sanjosestate: 'sanJoseState.png',
  savannahstate: 'savannahState.png',
  smu: 'smu.png',
  southalabama: 'southAlabama.png',
  southcarolina: 'southCarolina.png',
  southcarolinastate: 'southCarolinaState.png',
  southdakota: 'southDakota.png',
  southdakotastate: 'southDakotaState.png',
  southeasternlouisiana: 'southeasternLouisiana.png',
  southeastmissouristate: 'southeastMissouriState.png',
  southern: 'southern.png',
  southernillinois: 'southernIllinois.png',
  southernmississippi: 'southernMississippi.png',
  southernutah: 'southernUtah.png',
  southflorida: 'southFlorida.png',
  stanford: 'stanford.png',
  stephenfaustin: 'stephenFAustin.png',
  stetson: 'stetson.png',
  stfrancispa: 'stFrancisPA.png',
  stonybrook: 'stonyBrook.png',
  syracuse: 'syracuse.png',
  tcu: 'TCU.png',
  temple: 'temple.png',
  tennessee: 'tennessee.png',
  tennesseemartin: 'tennesseeMartin.png',
  tennesseestate: 'tennesseeState.png',
  tennesseetech: 'tennesseeTech.png',
  texas: 'texas.png',
  texasam: 'texasAM.png',
  texassanantonio: 'texasSanAntonio.png',
  texassouthern: 'texasSouthern.png',
  texasstate: 'texasState.png',
  texastech: 'texasTech.png',
  toledo: 'toledo.png',
  towson: 'towson.png',
  troy: 'troy.png',
  tulane: 'tulane.png',
  tulsa: 'tulsa.png',
  uab: 'uab.png',
  ucdavis: 'ucDavis.png',
  ucf: 'ucf.png',
  ucla: 'ucla.png',
  unlv: 'unlv.png',
  usc: 'usc.png',
  utah: 'utah.png',
  utahstate: 'utahState.png',
  utep: 'utep.png',
  valparaiso: 'valparaiso.png',
  vanderbilt: 'vanderbilt.png',
  villanova: 'villanova.png',
  virginia: 'virginia.png',
  virginiatech: 'virginiaTech.png',
  vmi: 'vmi.png',
  wagner: 'wagner.png',
  wakeforest: 'wakeForest.png',
  washburn: 'Washburn.png',
  washington: 'washington.png',
  washingtonstate: 'washingtonState.png',
  weberstate: 'weberState.png',
  westerncarolina: 'westernCarolina.png',
  westernillinois: 'westernIllinois.png',
  westernkentucky: 'westernKentucky.png',
  westernmichigan: 'westernMichigan.png',
  westvirginia: 'westVirginia.png',
  williammary: 'williamMary.png',
  wisconsin: 'wisconsin.png',
  wofford: 'wofford.png',
  wyoming: 'wyoming.png',
  yale: 'yale.png',
  youngstownstate: 'youngstownState.png',
};

/**
 * The game frequently uses abbreviated DisplayName values for opponents in
 * the schedule (e.g. "Washington St.", "UConn", "C. Carolina") rather than
 * the full names the logo filenames are keyed on. Verified against all 143
 * real teams in the save — these 28 are every real mismatch found; the
 * handful of "FCS East/West/..." placeholder names are intentionally left
 * unmapped since they're generic slots with no specific team/logo yet.
 */
const TEAM_NAME_ALIASES: Record<string, string> = {
  appst: 'appalachianstate',
  bostoncollege: 'boston',
  cmichigan: 'centralmichigan',
  ccarolina: 'coastalcarolina',
  uconn: 'connecticut',
  emichigan: 'easternmichigan',
  fiu: 'floridaintl',
  flaatlantic: 'floridaatlantic',
  gasouthern: 'georgiasouthern',
  jaxstate: 'jacksonvillestate',
  kennesawst: 'kennesawstate',
  louisiana: 'louisianalafayette',
  middletenn: 'middletennessee',
  mississippist: 'mississippistate',
  newmexicost: 'newmexicostate',
  ndsu: 'northdakotastate',
  niu: 'northernillinois',
  sacstate: 'sacramentostate',
  samhouston: 'samhoustonstate',
  sandiegost: 'sandiegostate',
  southernmiss: 'southernmississippi',
  ulmonroe: 'louisianamonroe',
  umass: 'massachusetts',
  usf: 'southflorida',
  utsa: 'texassanantonio',
  washingtonst: 'washingtonstate',
  wkentucky: 'westernkentucky',
  wmichigan: 'westernmichigan',
};

/**
 * Premium 3D-rendered logos (public/assets/3d_logos/png), keyed by the same
 * canonical team keys as TEAM_NCAA_LOGOS. Preferred at every size — the flat
 * NCAA logos remain the fallback for teams not covered by the 3D set. Keys not
 * present in the flat map (the FCS region placeholders) are additive: the 3D
 * set happens to include art for them.
 */
export const TEAM_3D_LOGOS: Record<string, string> = {
  airforce: 'AirForce.png',
  akron: 'Akron.png',
  alabama: 'Alabama.png',
  appalachianstate: 'AppalachianState.png',
  arizona: 'Arizona.png',
  arizonastate: 'ArizonaState.png',
  arkansas: 'Arkansas.png',
  arkansasstate: 'ArkansasState.png',
  army: 'Army.png',
  auburn: 'Auburn.png',
  ballstate: 'BallState.png',
  baylor: 'Baylor.png',
  boisestate: 'BoiseState.png',
  boston: 'BostonCollege.png',
  bowlinggreen: 'BowlingGreen.png',
  buffalo: 'Buffalo.png',
  byu: 'BYU.png',
  california: 'CAL.png',
  centralmichigan: 'CentralMichigan.png',
  charlotte: 'Charlotte.png',
  cincinnati: 'Cincinnati.png',
  clemson: 'Clemson.png',
  coastalcarolina: 'CoastalCarolina.png',
  colorado: 'Colorado.png',
  coloradostate: 'ColoradoState.png',
  connecticut: 'Connecticut.png',
  delaware: 'Delaware.png',
  duke: 'Duke.png',
  eastcarolina: 'ECU.png',
  easternmichigan: 'EasternMichigan.png',
  fcseast: 'FCSEast.png',
  fcsmidwest: 'FCSMidwest.png',
  fcsnorthwest: 'FCSNorthwest.png',
  fcssoutheast: 'FCSSoutheast.png',
  fcswest: 'FCSWest.png',
  florida: 'Florida.png',
  floridaatlantic: 'FloridaAtlantic.png',
  floridaintl: 'FIU.png',
  floridastate: 'FloridaState.png',
  fresnostate: 'FresnoState.png',
  georgia: 'Georgia.png',
  georgiasouthern: 'GeorgiaSouthern.png',
  georgiastate: 'GeorgiaState.png',
  georgiatech: 'GeorgiaTech.png',
  hawaii: 'Hawaii.png',
  houston: 'Houston.png',
  illinois: 'Illinois.png',
  indiana: 'Indiana.png',
  iowa: 'Iowa.png',
  iowastate: 'IowaState.png',
  jacksonvillestate: 'JacksonvilleState.png',
  jamesmadison: 'JamesMadison.png',
  kansas: 'Kansas.png',
  kansasstate: 'KansasState.png',
  kennesawstate: 'KennesawState.png',
  kentstate: 'KentState.png',
  kentucky: 'Kentucky.png',
  liberty: 'Liberty.png',
  louisianalafayette: 'Louisiana.png',
  louisianamonroe: 'ULMonroe.png',
  louisianatech: 'LouisianaTech.png',
  louisville: 'Louisville.png',
  lsu: 'LSU.png',
  marshall: 'Marshall.png',
  maryland: 'Maryland.png',
  massachusetts: 'UMass.png',
  memphis: 'Memphis.png',
  miami: 'Miami.png',
  miamioh: 'MiamiUniversity.png',
  michigan: 'Michigan.png',
  michiganstate: 'MichiganState.png',
  middletennessee: 'MidTennState.png',
  minnesota: 'Minnesota.png',
  mississippistate: 'MississippiState.png',
  missouri: 'Missouri.png',
  missouristate: 'MissouriState.png',
  navy: 'Navy.png',
  ncstate: 'NCState.png',
  nebraska: 'Nebraska.png',
  nevada: 'Nevada.png',
  newmexico: 'NewMexico.png',
  newmexicostate: 'NewMexicoState.png',
  northcarolina: 'NorthCarolina.png',
  northdakotastate: 'NorthDakotaState.png',
  northernillinois: 'NorthernIllinois.png',
  northtexas: 'NorthTexas.png',
  northwestern: 'Northwestern.png',
  notredame: 'NotreDame.png',
  ohio: 'Ohio.png',
  ohiostate: 'OhioState.png',
  oklahoma: 'Oklahoma.png',
  oklahomastate: 'OklahomaState.png',
  olddominion: 'OldDominion.png',
  olemiss: 'OleMiss.png',
  oregon: 'Oregon.png',
  oregonstate: 'OregonState.png',
  pennstate: 'PennState.png',
  pittsburgh: 'Pittsburgh.png',
  purdue: 'Purdue.png',
  rice: 'Rice.png',
  rutgers: 'Rutgers.png',
  sacramentostate: 'SacramentoState.png',
  samhoustonstate: 'SamHoustonState.png',
  sandiegostate: 'SanDiegoState.png',
  sanjosestate: 'SanJoseState.png',
  smu: 'SMU.png',
  southalabama: 'SouthAlabama.png',
  southcarolina: 'SouthCarolina.png',
  southernmississippi: 'SouthernMiss.png',
  southflorida: 'USF.png',
  stanford: 'Stanford.png',
  syracuse: 'Syracuse.png',
  tcu: 'TCU.png',
  temple: 'Temple.png',
  tennessee: 'Tennessee.png',
  texas: 'Texas.png',
  texasam: 'TexasAM.png',
  texassanantonio: 'UTSA.png',
  texasstate: 'TexasState.png',
  texastech: 'TexasTech.png',
  toledo: 'Toledo.png',
  troy: 'Troy.png',
  tulane: 'Tulane.png',
  tulsa: 'Tulsa.png',
  uab: 'UAB.png',
  ucf: 'UCF.png',
  ucla: 'UCLA.png',
  unlv: 'UNLV.png',
  usc: 'USC.png',
  utah: 'Utah.png',
  utahstate: 'UtahState.png',
  utep: 'UTEP.png',
  vanderbilt: 'Vanderbilt.png',
  virginia: 'Virginia.png',
  virginiatech: 'VirginiaTech.png',
  wakeforest: 'WakeForest.png',
  washington: 'Washington.png',
  washingtonstate: 'WashingtonState.png',
  westernkentucky: 'WesternKentucky.png',
  westernmichigan: 'WesternMichigan.png',
  westvirginia: 'WestVirginia.png',
  wisconsin: 'Wisconsin.png',
  wyoming: 'Wyoming.png',
};

const FALLBACK_LOGO = '_NCAA_logo.png';
const LOGO_BASE_PATH = 'assets/icons/ncaa-logos';
/**
 * "On dark" / "on light" variants — same 143 teams as TEAM_3D_LOGOS, filenames
 * verified to be identical apart from an `_OD`/`_OL` suffix before `.png`
 * (diffed all 3 folders directly), so they're derived rather than a second
 * 143-entry table that could drift out of sync.
 */
const THREE_D_OD_BASE_PATH = 'assets/3d_logos/PNG_OD';
// Real on-disk casing is "png_OL", not "PNG_OL" — confirmed via PowerShell
// (Get-ChildItem, exact-case) after `ls`/`find` misleadingly succeeded on the
// wrong case due to Windows' case-insensitive filesystem. Matters for
// portability: a packaged build on a case-sensitive filesystem would 404.
const THREE_D_OL_BASE_PATH = 'assets/3d_logos/png_OL';
/** Same 143 teams, `_gold` suffix instead of `_OD`/`_OL` — confirmed present on disk (e.g. `Miami_gold.png`). A celebratory variant, not a theme-appearance one: used for "this team just gained something" contexts (e.g. a newly-signed recruit) rather than picked automatically by light/dark appearance. */
const THREE_D_GOLD_BASE_PATH = 'assets/3d_logos/png_gold';

export const FALLBACK_LOGO_PATH = `${LOGO_BASE_PATH}/${FALLBACK_LOGO}`;

/**
 * Teams whose on-dark (`_OD`) 3D logo is pixel-for-pixel identical to the
 * on-light (`_OL`) one — a colorful mark that reads the same on either
 * background, so the game shipped the same image twice. Verified by a full
 * byte + pixel diff of all 144 OL/OD pairs (74 teams matched here; the
 * remaining 69 have a real light/dark recolor and keep both files). The
 * redundant `_OD` copies were removed from public/assets, so for these keys
 * getLogoPath serves the single `_OL` file for BOTH light and dark. Gold is
 * unaffected (a separate variant). Keep this in sync if the logo set changes.
 */
const SINGLE_VARIANT_LOGOS = new Set<string>([
  'appalachianstate', 'arizona', 'arizonastate', 'arkansas', 'arkansasstate', 'army',
  'ballstate', 'boisestate', 'bowlinggreen', 'buffalo', 'byu', 'coastalcarolina',
  'colorado', 'coloradostate', 'connecticut', 'delaware', 'eastcarolina', 'fcseast',
  'fcsmidwest', 'fcsnorthwest', 'fcssoutheast', 'fcswest', 'florida', 'floridaatlantic',
  'floridaintl', 'floridastate', 'fresnostate', 'georgiasouthern', 'georgiastate', 'hawaii',
  'iowastate', 'jacksonvillestate', 'jamesmadison', 'kansas', 'kansasstate', 'kennesawstate',
  'kentstate', 'liberty', 'louisianalafayette', 'louisianamonroe', 'louisianatech', 'louisville',
  'marshall', 'memphis', 'miami', 'miamioh', 'middletennessee', 'mississippistate',
  'missouri', 'missouristate', 'ncstate', 'newmexico', 'newmexicostate', 'northdakotastate',
  'northernillinois', 'ohio', 'ohiostate', 'oklahomastate', 'olddominion', 'oregonstate',
  'pennstate', 'sacramentostate', 'sandiegostate', 'sanjosestate', 'southalabama', 'southernmississippi',
  'stanford', 'texassanantonio', 'troy', 'tulane', 'uab', 'ucf',
  'westernkentucky', 'westernmichigan',
]);

export function normalizeTeamKey(teamAssetName: string): string {
  return teamAssetName.toLowerCase().trim().replace(/[^a-z0-9]/g, '');
}

/** Resolves a raw game DisplayName to its canonical team key (via normalization + alias). Exported so other lookups (e.g. stadiumData.ts) key on the same identity as logos. */
export function canonicalKey(teamAssetName: string): string {
  const key = normalizeTeamKey(teamAssetName);
  return TEAM_NAME_ALIASES[key] ?? key;
}

/**
 * Best available logo path, premium 3D preferred at every size and the flat
 * NCAA logo as fallback, then the generic mark. Because the 3D art is the same
 * source at all sizes, callers just render it smaller (see TeamLogo) rather
 * than swapping files per size.
 *
 * `background` picks the on-dark/on-light 3D variant (defaults to 'light' —
 * matches this app's default appearance), or the celebratory `'gold'` variant
 * (not tied to theme appearance — an explicit per-usage choice, see
 * TeamLogo's `variant` prop). Flat NCAA fallback logos have no dark/light/gold
 * variant and render as-is regardless.
 */
export function getLogoPath(teamAssetName: string, background: 'light' | 'dark' | 'gold' = 'light'): string {
  const key = canonicalKey(teamAssetName);
  const filename = TEAM_3D_LOGOS[key];
  if (filename) {
    if (background === 'gold') {
      return `${THREE_D_GOLD_BASE_PATH}/${filename.replace(/\.png$/i, '_gold.png')}`;
    }
    // Only genuine two-variant teams have a distinct on-dark file; for the
    // single-variant teams the _OD copy was removed, so serve _OL for dark too.
    const useDark = background === 'dark' && !SINGLE_VARIANT_LOGOS.has(key);
    const base = useDark ? THREE_D_OD_BASE_PATH : THREE_D_OL_BASE_PATH;
    const variantFilename = filename.replace(/\.png$/i, `_${useDark ? 'OD' : 'OL'}.png`);
    return `${base}/${variantFilename}`;
  }
  if (TEAM_NCAA_LOGOS[key]) return `${LOGO_BASE_PATH}/${TEAM_NCAA_LOGOS[key]}`;
  return FALLBACK_LOGO_PATH;
}
