import { programArtFor } from './programArt';
/**
 * NCAA logo asset mapping — generated from assets/icons/NCAA Logos/*.webp
 * Maps a normalized team key (lowercase, alphanumeric-only) to its logo filename.
 */

export const TEAM_NCAA_LOGOS: Record<string, string> = {
  abilenechristian: 'abileneChristian.webp',
  airforce: 'airForce.webp',
  akron: 'akron.webp',
  alabama: 'alabama.webp',
  alabamaam: 'alabamaAM.webp',
  alabamastate: 'alabamaState.webp',
  albany: 'albany.webp',
  alcornstate: 'alcornState.webp',
  appalachianstate: 'appalachianState.webp',
  arizona: 'arizona.webp',
  arizonastate: 'arizonaState.webp',
  arkansas: 'arkansas.webp',
  arkansaspinebluff: 'arkansasPineBluff.webp',
  arkansasstate: 'arkansasState.webp',
  army: 'army.webp',
  auburn: 'auburn.webp',
  austinpeay: 'austinPeay.webp',
  ballstate: 'ballState.webp',
  baylor: 'baylor.webp',
  bethunecookman: 'bethuneCookman.webp',
  boisestate: 'boiseState.webp',
  boston: 'boston.webp',
  bowlinggreen: 'bowlingGreen.webp',
  brown: 'brown.webp',
  bryant: 'bryant.webp',
  bucknell: 'bucknell.webp',
  buffalo: 'buffalo.webp',
  butler: 'butler.webp',
  byu: 'byu.webp',
  california: 'california.webp',
  calpoly: 'calPoly.webp',
  campbell: 'campbell.webp',
  centralarkansas: 'centralArkansas.webp',
  centralconnecticut: 'centralConnecticut.webp',
  centralmichigan: 'centralMichigan.webp',
  charlestonsouthern: 'charlestonSouthern.webp',
  charlotte: 'charlotte.webp',
  chattanooga: 'chattanooga.webp',
  cincinnati: 'cincinnati.webp',
  citadel: 'citadel.webp',
  clemson: 'clemson.webp',
  coastalcarolina: 'coastalCarolina.webp',
  colgate: 'colgate.webp',
  colorado: 'colorado.webp',
  coloradostate: 'coloradoState.webp',
  columbia: 'columbia.webp',
  connecticut: 'connecticut.webp',
  cornell: 'cornell.webp',
  dartmouth: 'dartmouth.webp',
  davidson: 'davidson.webp',
  dayton: 'dayton.webp',
  delaware: 'delaware.webp',
  delawarestate: 'delawareState.webp',
  drake: 'drake.webp',
  duke: 'duke.webp',
  duquesne: 'duquesne.webp',
  eastcarolina: 'eastCarolina.webp',
  easternillinois: 'easternIllinois.webp',
  easternkentucky: 'easternKentucky.webp',
  easternmichigan: 'easternMichigan.webp',
  easternwashington: 'easternWashington.webp',
  easttennessee: 'eastTennessee.webp',
  elon: 'elon.webp',
  florida: 'florida.webp',
  floridaam: 'floridaAM.webp',
  floridaatlantic: 'floridaAtlantic.webp',
  floridaintl: 'floridaIntl.webp',
  floridastate: 'floridaState.webp',
  fordham: 'fordham.webp',
  fresnostate: 'fresnoState.webp',
  furman: 'furman.webp',
  gardnerwebb: 'gardnerWebb.webp',
  georgetown: 'georgetown.webp',
  georgia: 'georgia.webp',
  georgiasouthern: 'georgiaSouthern.webp',
  georgiastate: 'georgiaState.webp',
  georgiatech: 'georgiaTech.webp',
  gramblingstate: 'gramblingState.webp',
  hampton: 'hampton.webp',
  harvard: 'harvard.webp',
  hawaii: 'hawaii.webp',
  holycross: 'holyCross.webp',
  houston: 'houston.webp',
  houstonbaptist: 'houstonBaptist.webp',
  howard: 'howard.webp',
  idaho: 'idaho.webp',
  idahostate: 'idahoState.webp',
  illinois: 'illinois.webp',
  illinoisstate: 'illinoisState.webp',
  incarnateword: 'incarnateWord.webp',
  indiana: 'indiana.webp',
  indianastate: 'indianaState.webp',
  iowa: 'iowa.webp',
  iowastate: 'iowaState.webp',
  jacksonstate: 'jacksonState.webp',
  jacksonville: 'jacksonville.webp',
  jacksonvillestate: 'jacksonvilleState.webp',
  jamesmadison: 'jamesMadison.webp',
  kansas: 'kansas.webp',
  kansasstate: 'kansasState.webp',
  kennesawstate: 'kennesawState.webp',
  kentstate: 'kentState.webp',
  kentucky: 'kentucky.webp',
  lafayette: 'lafayette.webp',
  lamar: 'lamar.webp',
  lehigh: 'lehigh.webp',
  liberty: 'liberty.webp',
  louisianalafayette: 'louisianaLafayette.webp',
  louisianamonroe: 'louisianaMonroe.webp',
  louisianatech: 'LouisianaTech.webp',
  louisville: 'louisville.webp',
  lsu: 'lsu.webp',
  maine: 'maine.webp',
  marist: 'marist.webp',
  marshall: 'marshall.webp',
  maryland: 'maryland.webp',
  massachusetts: 'massachusetts.webp',
  mcneesestate: 'mcNeeseState.webp',
  memphis: 'memphis.webp',
  mercer: 'mercer.webp',
  miami: 'miami.webp',
  miamioh: 'miamiOH.webp',
  michigan: 'michigan.webp',
  michiganstate: 'michiganState.webp',
  middletennessee: 'middleTennessee.webp',
  minnesota: 'minnesota.webp',
  mississippistate: 'mississippiState.webp',
  mississippivalleystate: 'mississippiValleyState.webp',
  missouri: 'missouri.webp',
  missouristate: 'missouriState.webp',
  monmouth: 'monmouth.webp',
  montana: 'montana.webp',
  montanastate: 'montanaState.webp',
  moreheadstate: 'moreheadState.webp',
  morganstate: 'morganState.webp',
  murraystate: 'murrayState.webp',
  navy: 'navy.webp',
  ncstate: 'ncState.webp',
  nebraska: 'nebraska.webp',
  nevada: 'nevada.webp',
  newhampshire: 'newHampshire.webp',
  newmexico: 'newMexico.webp',
  newmexicostate: 'newMexicoState.webp',
  nichollsstate: 'nichollsState.webp',
  norfolkstate: 'norfolkState.webp',
  northcarolina: 'northCarolina.webp',
  northcarolinaat: 'northCarolinaAT.webp',
  northcarolinacentral: 'northCarolinaCentral.webp',
  northdakota: 'northDakota.webp',
  northdakotastate: 'northDakotaState.webp',
  northernarizona: 'northernArizona.webp',
  northerncolorado: 'northernColorado.webp',
  northernillinois: 'northernIllinois.webp',
  northerniowa: 'northernIowa.webp',
  northtexas: 'northTexas.webp',
  northwestern: 'northwestern.webp',
  northwesternstate: 'northwesternState.webp',
  notredame: 'notreDame.webp',
  ohio: 'ohio.webp',
  ohiostate: 'ohioState.webp',
  oklahoma: 'oklahoma.webp',
  oklahomastate: 'OklahomaState.webp',
  olddominion: 'oldDominion.webp',
  olemiss: 'oleMiss.webp',
  oregon: 'oregon.webp',
  oregonstate: 'oregonState.webp',
  penn: 'penn.webp',
  pennstate: 'pennState.webp',
  pittsburgh: 'pittsburgh.webp',
  portlandstate: 'portlandState.webp',
  prairieview: 'prairieView.webp',
  presbyteriancollege: 'presbyterianCollege.webp',
  princeton: 'princeton.webp',
  purdue: 'purdue.webp',
  rhodeisland: 'rhodeIsland.webp',
  rice: 'rice.webp',
  richmond: 'richmond.webp',
  robertmorris: 'robertMorris.webp',
  rutgers: 'rutgers.webp',
  sacramentostate: 'sacramentoState.webp',
  sacredheart: 'sacredHeart.webp',
  samford: 'samford.webp',
  samhoustonstate: 'samHoustonState.webp',
  sandiego: 'sanDiego.webp',
  sandiegostate: 'sanDiegoState.webp',
  sanjosestate: 'sanJoseState.webp',
  savannahstate: 'savannahState.webp',
  smu: 'smu.webp',
  southalabama: 'southAlabama.webp',
  southcarolina: 'southCarolina.webp',
  southcarolinastate: 'southCarolinaState.webp',
  southdakota: 'southDakota.webp',
  southdakotastate: 'southDakotaState.webp',
  southeasternlouisiana: 'southeasternLouisiana.webp',
  southeastmissouristate: 'southeastMissouriState.webp',
  southern: 'southern.webp',
  southernillinois: 'southernIllinois.webp',
  southernmississippi: 'southernMississippi.webp',
  southernutah: 'southernUtah.webp',
  southflorida: 'southFlorida.webp',
  stanford: 'stanford.webp',
  stephenfaustin: 'stephenFAustin.webp',
  stetson: 'stetson.webp',
  stfrancispa: 'stFrancisPA.webp',
  stonybrook: 'stonyBrook.webp',
  syracuse: 'syracuse.webp',
  tcu: 'TCU.webp',
  temple: 'temple.webp',
  tennessee: 'tennessee.webp',
  tennesseemartin: 'tennesseeMartin.webp',
  tennesseestate: 'tennesseeState.webp',
  tennesseetech: 'tennesseeTech.webp',
  texas: 'texas.webp',
  texasam: 'texasAM.webp',
  texassanantonio: 'texasSanAntonio.webp',
  texassouthern: 'texasSouthern.webp',
  texasstate: 'texasState.webp',
  texastech: 'texasTech.webp',
  toledo: 'toledo.webp',
  towson: 'towson.webp',
  troy: 'troy.webp',
  tulane: 'tulane.webp',
  tulsa: 'tulsa.webp',
  uab: 'uab.webp',
  ucdavis: 'ucDavis.webp',
  ucf: 'ucf.webp',
  ucla: 'ucla.webp',
  unlv: 'unlv.webp',
  usc: 'usc.webp',
  utah: 'utah.webp',
  utahstate: 'utahState.webp',
  utep: 'utep.webp',
  valparaiso: 'valparaiso.webp',
  vanderbilt: 'vanderbilt.webp',
  villanova: 'villanova.webp',
  virginia: 'virginia.webp',
  virginiatech: 'virginiaTech.webp',
  vmi: 'vmi.webp',
  wagner: 'wagner.webp',
  wakeforest: 'wakeForest.webp',
  washburn: 'Washburn.webp',
  washington: 'washington.webp',
  washingtonstate: 'washingtonState.webp',
  weberstate: 'weberState.webp',
  westerncarolina: 'westernCarolina.webp',
  westernillinois: 'westernIllinois.webp',
  westernkentucky: 'westernKentucky.webp',
  westernmichigan: 'westernMichigan.webp',
  westvirginia: 'westVirginia.webp',
  williammary: 'williamMary.webp',
  wisconsin: 'wisconsin.webp',
  wofford: 'wofford.webp',
  wyoming: 'wyoming.webp',
  yale: 'yale.webp',
  youngstownstate: 'youngstownState.webp',
};

/**
 * The game frequently uses abbreviated DisplayName values for opponents in
 * the schedule (e.g. "Washington St.", "UConn", "C. Carolina") rather than
 * the full names the logo filenames are keyed on. Verified against all 143
 * real teams in the save — these 28 are every real mismatch found; the
 * handful of "FCS East/West/..." placeholder names are intentionally left
 * unmapped since they're generic slots with no specific team/logo yet.
 */
const TEAM_NAME_ALIASES: Record<string, string> = {
  appst: 'appalachianstate',
  bostoncollege: 'boston',
  cmichigan: 'centralmichigan',
  ccarolina: 'coastalcarolina',
  uconn: 'connecticut',
  emichigan: 'easternmichigan',
  fiu: 'floridaintl',
  flaatlantic: 'floridaatlantic',
  gasouthern: 'georgiasouthern',
  jaxstate: 'jacksonvillestate',
  kennesawst: 'kennesawstate',
  louisiana: 'louisianalafayette',
  middletenn: 'middletennessee',
  mississippist: 'mississippistate',
  newmexicost: 'newmexicostate',
  ndsu: 'northdakotastate',
  niu: 'northernillinois',
  sacstate: 'sacramentostate',
  samhouston: 'samhoustonstate',
  sandiegost: 'sandiegostate',
  southernmiss: 'southernmississippi',
  ulmonroe: 'louisianamonroe',
  umass: 'massachusetts',
  usf: 'southflorida',
  utsa: 'texassanantonio',
  washingtonst: 'washingtonstate',
  wkentucky: 'westernkentucky',
  wmichigan: 'westernmichigan',
};

/**
 * Premium 3D-rendered logos (public/assets/3d_logos/png), keyed by the same
 * canonical team keys as TEAM_NCAA_LOGOS. Preferred at every size — the flat
 * NCAA logos remain the fallback for teams not covered by the 3D set. Keys not
 * present in the flat map (the FCS region placeholders) are additive: the 3D
 * set happens to include art for them.
 */
export const TEAM_3D_LOGOS: Record<string, string> = {
  airforce: 'AirForce.webp',
  akron: 'Akron.webp',
  alabama: 'Alabama.webp',
  appalachianstate: 'AppalachianState.webp',
  arizona: 'Arizona.webp',
  arizonastate: 'ArizonaState.webp',
  arkansas: 'Arkansas.webp',
  arkansasstate: 'ArkansasState.webp',
  army: 'Army.webp',
  auburn: 'Auburn.webp',
  ballstate: 'BallState.webp',
  baylor: 'Baylor.webp',
  boisestate: 'BoiseState.webp',
  boston: 'BostonCollege.webp',
  bowlinggreen: 'BowlingGreen.webp',
  buffalo: 'Buffalo.webp',
  byu: 'BYU.webp',
  california: 'CAL.webp',
  centralmichigan: 'CentralMichigan.webp',
  charlotte: 'Charlotte.webp',
  cincinnati: 'Cincinnati.webp',
  clemson: 'Clemson.webp',
  coastalcarolina: 'CoastalCarolina.webp',
  colorado: 'Colorado.webp',
  coloradostate: 'ColoradoState.webp',
  connecticut: 'Connecticut.webp',
  delaware: 'Delaware.webp',
  duke: 'Duke.webp',
  eastcarolina: 'ECU.webp',
  easternmichigan: 'EasternMichigan.webp',
  fcseast: 'FCSEast.webp',
  fcsmidwest: 'FCSMidwest.webp',
  fcsnorthwest: 'FCSNorthwest.webp',
  fcssoutheast: 'FCSSoutheast.webp',
  fcswest: 'FCSWest.webp',
  florida: 'Florida.webp',
  floridaatlantic: 'FloridaAtlantic.webp',
  floridaintl: 'FIU.webp',
  floridastate: 'FloridaState.webp',
  fresnostate: 'FresnoState.webp',
  georgia: 'Georgia.webp',
  georgiasouthern: 'GeorgiaSouthern.webp',
  georgiastate: 'GeorgiaState.webp',
  georgiatech: 'GeorgiaTech.webp',
  hawaii: 'Hawaii.webp',
  houston: 'Houston.webp',
  illinois: 'Illinois.webp',
  indiana: 'Indiana.webp',
  iowa: 'Iowa.webp',
  iowastate: 'IowaState.webp',
  jacksonvillestate: 'JacksonvilleState.webp',
  jamesmadison: 'JamesMadison.webp',
  kansas: 'Kansas.webp',
  kansasstate: 'KansasState.webp',
  kennesawstate: 'KennesawState.webp',
  kentstate: 'KentState.webp',
  kentucky: 'Kentucky.webp',
  liberty: 'Liberty.webp',
  louisianalafayette: 'Louisiana.webp',
  louisianamonroe: 'ULMonroe.webp',
  louisianatech: 'LouisianaTech.webp',
  louisville: 'Louisville.webp',
  lsu: 'LSU.webp',
  marshall: 'Marshall.webp',
  maryland: 'Maryland.webp',
  massachusetts: 'UMass.webp',
  memphis: 'Memphis.webp',
  miami: 'Miami.webp',
  miamioh: 'MiamiUniversity.webp',
  michigan: 'Michigan.webp',
  michiganstate: 'MichiganState.webp',
  middletennessee: 'MidTennState.webp',
  minnesota: 'Minnesota.webp',
  mississippistate: 'MississippiState.webp',
  missouri: 'Missouri.webp',
  missouristate: 'MissouriState.webp',
  navy: 'Navy.webp',
  ncstate: 'NCState.webp',
  nebraska: 'Nebraska.webp',
  nevada: 'Nevada.webp',
  newmexico: 'NewMexico.webp',
  newmexicostate: 'NewMexicoState.webp',
  northcarolina: 'NorthCarolina.webp',
  northdakotastate: 'NorthDakotaState.webp',
  northernillinois: 'NorthernIllinois.webp',
  northtexas: 'NorthTexas.webp',
  northwestern: 'Northwestern.webp',
  notredame: 'NotreDame.webp',
  ohio: 'Ohio.webp',
  ohiostate: 'OhioState.webp',
  oklahoma: 'Oklahoma.webp',
  oklahomastate: 'OklahomaState.webp',
  olddominion: 'OldDominion.webp',
  olemiss: 'OleMiss.webp',
  oregon: 'Oregon.webp',
  oregonstate: 'OregonState.webp',
  pennstate: 'PennState.webp',
  pittsburgh: 'Pittsburgh.webp',
  purdue: 'Purdue.webp',
  rice: 'Rice.webp',
  rutgers: 'Rutgers.webp',
  sacramentostate: 'SacramentoState.webp',
  samhoustonstate: 'SamHoustonState.webp',
  sandiegostate: 'SanDiegoState.webp',
  sanjosestate: 'SanJoseState.webp',
  smu: 'SMU.webp',
  southalabama: 'SouthAlabama.webp',
  southcarolina: 'SouthCarolina.webp',
  southernmississippi: 'SouthernMiss.webp',
  southflorida: 'USF.webp',
  stanford: 'Stanford.webp',
  syracuse: 'Syracuse.webp',
  tcu: 'TCU.webp',
  temple: 'Temple.webp',
  tennessee: 'Tennessee.webp',
  texas: 'Texas.webp',
  texasam: 'TexasAM.webp',
  texassanantonio: 'UTSA.webp',
  texasstate: 'TexasState.webp',
  texastech: 'TexasTech.webp',
  toledo: 'Toledo.webp',
  troy: 'Troy.webp',
  tulane: 'Tulane.webp',
  tulsa: 'Tulsa.webp',
  uab: 'UAB.webp',
  ucf: 'UCF.webp',
  ucla: 'UCLA.webp',
  unlv: 'UNLV.webp',
  usc: 'USC.webp',
  utah: 'Utah.webp',
  utahstate: 'UtahState.webp',
  utep: 'UTEP.webp',
  vanderbilt: 'Vanderbilt.webp',
  virginia: 'Virginia.webp',
  virginiatech: 'VirginiaTech.webp',
  wakeforest: 'WakeForest.webp',
  washington: 'Washington.webp',
  washingtonstate: 'WashingtonState.webp',
  westernkentucky: 'WesternKentucky.webp',
  westernmichigan: 'WesternMichigan.webp',
  westvirginia: 'WestVirginia.webp',
  wisconsin: 'Wisconsin.webp',
  wyoming: 'Wyoming.webp',
};

const FALLBACK_LOGO = '_NCAA_logo.webp';
const LOGO_BASE_PATH = 'cfbmedia://media/icons/ncaa-logos';
/**
 * "On dark" / "on light" variants — same 143 teams as TEAM_3D_LOGOS, filenames
 * verified to be identical apart from an `_OD`/`_OL` suffix before `.webp`
 * (diffed all 3 folders directly), so they're derived rather than a second
 * 143-entry table that could drift out of sync.
 */
const THREE_D_OD_BASE_PATH = 'cfbmedia://media/3d_logos/PNG_OD';
// Real on-disk casing is "png_OL", not "PNG_OL" — confirmed via PowerShell
// (Get-ChildItem, exact-case) after `ls`/`find` misleadingly succeeded on the
// wrong case due to Windows' case-insensitive filesystem. Matters for
// portability: a packaged build on a case-sensitive filesystem would 404.
const THREE_D_OL_BASE_PATH = 'cfbmedia://media/3d_logos/png_OL';
/** Same 143 teams, `_gold` suffix instead of `_OD`/`_OL` — confirmed present on disk (e.g. `Miami_gold.webp`). A celebratory variant, not a theme-appearance one: used for "this team just gained something" contexts (e.g. a newly-signed recruit) rather than picked automatically by light/dark appearance. */
const THREE_D_GOLD_BASE_PATH = 'cfbmedia://media/3d_logos/png_gold';

export const FALLBACK_LOGO_PATH = `${LOGO_BASE_PATH}/${FALLBACK_LOGO}`;

/**
 * Teams whose on-dark (`_OD`) 3D logo is pixel-for-pixel identical to the
 * on-light (`_OL`) one — a colorful mark that reads the same on either
 * background, so the game shipped the same image twice. Verified by a full
 * byte + pixel diff of all 144 OL/OD pairs (74 teams matched here; the
 * remaining 69 have a real light/dark recolor and keep both files). The
 * redundant `_OD` copies were removed from public/assets, so for these keys
 * getLogoPath serves the single `_OL` file for BOTH light and dark. Gold is
 * unaffected (a separate variant). Keep this in sync if the logo set changes.
 */
const SINGLE_VARIANT_LOGOS = new Set<string>([
  'appalachianstate', 'arizona', 'arizonastate', 'arkansas', 'arkansasstate', 'army',
  'ballstate', 'boisestate', 'bowlinggreen', 'buffalo', 'byu', 'coastalcarolina',
  'colorado', 'coloradostate', 'connecticut', 'delaware', 'eastcarolina', 'fcseast',
  'fcsmidwest', 'fcsnorthwest', 'fcssoutheast', 'fcswest', 'florida', 'floridaatlantic',
  'floridaintl', 'floridastate', 'fresnostate', 'georgiasouthern', 'georgiastate', 'hawaii',
  'iowastate', 'jacksonvillestate', 'jamesmadison', 'kansas', 'kansasstate', 'kennesawstate',
  'kentstate', 'liberty', 'louisianalafayette', 'louisianamonroe', 'louisianatech', 'louisville',
  'marshall', 'memphis', 'miami', 'miamioh', 'middletennessee', 'mississippistate',
  'missouri', 'missouristate', 'ncstate', 'newmexico', 'newmexicostate', 'northdakotastate',
  'northernillinois', 'ohio', 'ohiostate', 'oklahomastate', 'olddominion', 'oregonstate',
  'pennstate', 'sacramentostate', 'sandiegostate', 'sanjosestate', 'southalabama', 'southernmississippi',
  'stanford', 'texassanantonio', 'troy', 'tulane', 'uab', 'ucf',
  'westernkentucky', 'westernmichigan',
]);

export function normalizeTeamKey(teamAssetName: string): string {
  return teamAssetName.toLowerCase().trim().replace(/[^a-z0-9]/g, '');
}

/** Resolves a raw game DisplayName to its canonical team key (via normalization + alias). Exported so other lookups (e.g. stadiumData.ts) key on the same identity as logos. */
export function canonicalKey(teamAssetName: string): string {
  const key = normalizeTeamKey(teamAssetName);
  return TEAM_NAME_ALIASES[key] ?? key;
}

/**
 * Best available logo path, premium 3D preferred at every size and the flat
 * NCAA logo as fallback, then the generic mark. Because the 3D art is the same
 * source at all sizes, callers just render it smaller (see TeamLogo) rather
 * than swapping files per size.
 *
 * `background` picks the on-dark/on-light 3D variant (defaults to 'light' —
 * matches this app's default appearance), or the celebratory `'gold'` variant
 * (not tied to theme appearance — an explicit per-usage choice, see
 * TeamLogo's `variant` prop). Flat NCAA fallback logos have no dark/light/gold
 * variant and render as-is regardless.
 */
export function getLogoPath(teamAssetName: string, background: 'light' | 'dark' | 'gold' = 'light'): string {
  const key = canonicalKey(teamAssetName);
  // An upload wins over the shipped library, and one file serves all three
  // variants: an arbitrary image has no on-dark or gold counterpart to pick,
  // so TeamLogo tints the gold case rather than this returning a file that
  // doesn't exist. See programArt.ts.
  const uploaded = programArtFor(key, 'logo');
  if (uploaded) return uploaded;
  const filename = TEAM_3D_LOGOS[key];
  if (filename) {
    if (background === 'gold') {
      return `${THREE_D_GOLD_BASE_PATH}/${filename.replace(/\.webp$/i, '_gold.webp')}`;
    }
    // Only genuine two-variant teams have a distinct on-dark file; for the
    // single-variant teams the _OD copy was removed, so serve _OL for dark too.
    const useDark = background === 'dark' && !SINGLE_VARIANT_LOGOS.has(key);
    const base = useDark ? THREE_D_OD_BASE_PATH : THREE_D_OL_BASE_PATH;
    const variantFilename = filename.replace(/\.webp$/i, `_${useDark ? 'OD' : 'OL'}.webp`);
    return `${base}/${variantFilename}`;
  }
  if (TEAM_NCAA_LOGOS[key]) return `${LOGO_BASE_PATH}/${TEAM_NCAA_LOGOS[key]}`;
  return FALLBACK_LOGO_PATH;
}
