import { canonicalKey } from './assetMapping';

/**
 * Where each school IS — the campus town, not the stadium.
 *
 * NOT IN THE SAVE, and that is checked rather than assumed. `Team` carries both
 * a `City` and a `Stadium` reference, so the game clearly models this, but on a
 * real dynasty save the `City` table has capacity 32 and ZERO populated rows
 * (`Stadium`: 183 and zero), and both resolve to nothing for all 143 team rows.
 * The strings live in a catalogue outside the save, like the AD contract-goal
 * wording. So this is authored reference data.
 *
 * DELIBERATELY SEPARATE FROM `stadiumData.ts`, which also has a city — they
 * answer different questions and must not be merged. That one is where a team
 * PLAYS; this one is where the school IS. Measured across the 138 FBS programs,
 * they disagree on six, and the differences are not trivial:
 *
 *   UCLA            plays Pasadena, CA        is Los Angeles, CA
 *   Miami           plays Miami Gardens, FL   is Coral Gables, FL
 *   UNLV            plays Paradise, NV        is Las Vegas, NV
 *   UConn           plays East Hartford, CT   is Storrs, CT
 *   Air Force       plays Colorado Springs    is USAF Academy
 *   Boston College  plays Boston, MA          is Chestnut Hill, MA
 *
 * A masthead reading "UCLA — Pasadena, CA" is simply wrong, which is why the
 * stadium table cannot serve this purpose. Use `stadiumData` for venues and
 * this for identity.
 *
 * KEYED ON `canonicalKey`, the same identity logos and stadium data already
 * use, so a lookup by any in-game DisplayName resolves exactly as a logo does —
 * aliases ("App St." -> appalachianstate) included. Generated by running the
 * app's own normaliser over the 138 FBS teams in a real save, not hand-typed:
 * 138 entries, 138 distinct keys, no collisions.
 *
 * WATCH OUT — all real, all easy to get wrong:
 *   - Miami (OH) is in OXFORD, OHIO. Not Miami, not Florida.
 *   - Jax State is Jacksonville, ALABAMA. Not Florida.
 *   - Bowling Green is Ohio; W. Kentucky is in Bowling Green, KENTUCKY.
 *   - Missouri State is Springfield, MISSOURI.
 *   - Columbia is both South Carolina and Missouri; Athens is both Georgia and
 *     Ohio; Oxford is both Mississippi and Ohio.
 */

export interface SchoolLocation {
  /** The campus town. */
  city: string;
  /** Full state name, matching the spelling the save uses for player `homeState`. */
  state: string;
  /** USPS two-letter code — what a masthead wants. */
  stateCode: string;
  /**
   * The recognisable city, where the campus town isn't it. Absent when `city`
   * is already the well-known name. Prefer this for anything pictorial: nobody
   * has a mental image of "University Park, PA", but everyone has one of State
   * College. 17 of 138 need it.
   */
  metro?: string;
}

export const SCHOOL_LOCATIONS: Readonly<Record<string, SchoolLocation>> = {
  airforce: { city: 'USAF Academy', state: 'Colorado', stateCode: 'CO', metro: 'Colorado Springs' }, // Air Force
  akron: { city: 'Akron', state: 'Ohio', stateCode: 'OH' }, // Akron
  alabama: { city: 'Tuscaloosa', state: 'Alabama', stateCode: 'AL' }, // Alabama
  appalachianstate: { city: 'Boone', state: 'North Carolina', stateCode: 'NC' }, // App St.
  arizona: { city: 'Tucson', state: 'Arizona', stateCode: 'AZ' }, // Arizona
  arizonastate: { city: 'Tempe', state: 'Arizona', stateCode: 'AZ', metro: 'Phoenix' }, // Arizona State
  arkansas: { city: 'Fayetteville', state: 'Arkansas', stateCode: 'AR' }, // Arkansas
  arkansasstate: { city: 'Jonesboro', state: 'Arkansas', stateCode: 'AR' }, // Arkansas State
  army: { city: 'West Point', state: 'New York', stateCode: 'NY' }, // Army
  auburn: { city: 'Auburn', state: 'Alabama', stateCode: 'AL' }, // Auburn
  ballstate: { city: 'Muncie', state: 'Indiana', stateCode: 'IN' }, // Ball State
  baylor: { city: 'Waco', state: 'Texas', stateCode: 'TX' }, // Baylor
  boisestate: { city: 'Boise', state: 'Idaho', stateCode: 'ID' }, // Boise State
  boston: { city: 'Chestnut Hill', state: 'Massachusetts', stateCode: 'MA', metro: 'Boston' }, // Boston College
  bowlinggreen: { city: 'Bowling Green', state: 'Ohio', stateCode: 'OH' }, // Bowling Green
  buffalo: { city: 'Buffalo', state: 'New York', stateCode: 'NY' }, // Buffalo
  byu: { city: 'Provo', state: 'Utah', stateCode: 'UT' }, // BYU
  california: { city: 'Berkeley', state: 'California', stateCode: 'CA' }, // California
  centralmichigan: { city: 'Mount Pleasant', state: 'Michigan', stateCode: 'MI' }, // C. Michigan
  charlotte: { city: 'Charlotte', state: 'North Carolina', stateCode: 'NC' }, // Charlotte
  cincinnati: { city: 'Cincinnati', state: 'Ohio', stateCode: 'OH' }, // Cincinnati
  clemson: { city: 'Clemson', state: 'South Carolina', stateCode: 'SC' }, // Clemson
  coastalcarolina: { city: 'Conway', state: 'South Carolina', stateCode: 'SC', metro: 'Myrtle Beach' }, // C. Carolina
  colorado: { city: 'Boulder', state: 'Colorado', stateCode: 'CO' }, // Colorado
  coloradostate: { city: 'Fort Collins', state: 'Colorado', stateCode: 'CO' }, // Colorado State
  connecticut: { city: 'Storrs', state: 'Connecticut', stateCode: 'CT', metro: 'Hartford' }, // UConn
  delaware: { city: 'Newark', state: 'Delaware', stateCode: 'DE' }, // Delaware
  duke: { city: 'Durham', state: 'North Carolina', stateCode: 'NC' }, // Duke
  eastcarolina: { city: 'Greenville', state: 'North Carolina', stateCode: 'NC' }, // East Carolina
  easternmichigan: { city: 'Ypsilanti', state: 'Michigan', stateCode: 'MI' }, // E. Michigan
  florida: { city: 'Gainesville', state: 'Florida', stateCode: 'FL' }, // Florida
  floridaatlantic: { city: 'Boca Raton', state: 'Florida', stateCode: 'FL' }, // FLA Atlantic
  floridaintl: { city: 'Miami', state: 'Florida', stateCode: 'FL' }, // FIU
  floridastate: { city: 'Tallahassee', state: 'Florida', stateCode: 'FL' }, // Florida State
  fresnostate: { city: 'Fresno', state: 'California', stateCode: 'CA' }, // Fresno State
  georgia: { city: 'Athens', state: 'Georgia', stateCode: 'GA' }, // Georgia
  georgiasouthern: { city: 'Statesboro', state: 'Georgia', stateCode: 'GA' }, // Ga Southern
  georgiastate: { city: 'Atlanta', state: 'Georgia', stateCode: 'GA' }, // Georgia State
  georgiatech: { city: 'Atlanta', state: 'Georgia', stateCode: 'GA' }, // Georgia Tech
  hawaii: { city: 'Honolulu', state: 'Hawaii', stateCode: 'HI' }, // Hawai'i
  houston: { city: 'Houston', state: 'Texas', stateCode: 'TX' }, // Houston
  illinois: { city: 'Champaign', state: 'Illinois', stateCode: 'IL' }, // Illinois
  indiana: { city: 'Bloomington', state: 'Indiana', stateCode: 'IN' }, // Indiana
  iowa: { city: 'Iowa City', state: 'Iowa', stateCode: 'IA' }, // Iowa
  iowastate: { city: 'Ames', state: 'Iowa', stateCode: 'IA' }, // Iowa State
  jacksonvillestate: { city: 'Jacksonville', state: 'Alabama', stateCode: 'AL' }, // Jax State
  jamesmadison: { city: 'Harrisonburg', state: 'Virginia', stateCode: 'VA' }, // James Madison
  kansas: { city: 'Lawrence', state: 'Kansas', stateCode: 'KS' }, // Kansas
  kansasstate: { city: 'Manhattan', state: 'Kansas', stateCode: 'KS' }, // Kansas State
  kennesawstate: { city: 'Kennesaw', state: 'Georgia', stateCode: 'GA', metro: 'Atlanta' }, // Kennesaw St.
  kentstate: { city: 'Kent', state: 'Ohio', stateCode: 'OH' }, // Kent State
  kentucky: { city: 'Lexington', state: 'Kentucky', stateCode: 'KY' }, // Kentucky
  liberty: { city: 'Lynchburg', state: 'Virginia', stateCode: 'VA' }, // Liberty
  louisianalafayette: { city: 'Lafayette', state: 'Louisiana', stateCode: 'LA' }, // Louisiana
  louisianamonroe: { city: 'Monroe', state: 'Louisiana', stateCode: 'LA' }, // UL Monroe
  louisianatech: { city: 'Ruston', state: 'Louisiana', stateCode: 'LA' }, // Louisiana Tech
  louisville: { city: 'Louisville', state: 'Kentucky', stateCode: 'KY' }, // Louisville
  lsu: { city: 'Baton Rouge', state: 'Louisiana', stateCode: 'LA' }, // LSU
  marshall: { city: 'Huntington', state: 'West Virginia', stateCode: 'WV' }, // Marshall
  maryland: { city: 'College Park', state: 'Maryland', stateCode: 'MD', metro: 'Washington, D.C.' }, // Maryland
  massachusetts: { city: 'Amherst', state: 'Massachusetts', stateCode: 'MA' }, // UMass
  memphis: { city: 'Memphis', state: 'Tennessee', stateCode: 'TN' }, // Memphis
  miami: { city: 'Coral Gables', state: 'Florida', stateCode: 'FL', metro: 'Miami' }, // Miami
  miamioh: { city: 'Oxford', state: 'Ohio', stateCode: 'OH' }, // Miami (OH)
  michigan: { city: 'Ann Arbor', state: 'Michigan', stateCode: 'MI' }, // Michigan
  michiganstate: { city: 'East Lansing', state: 'Michigan', stateCode: 'MI', metro: 'Lansing' }, // Michigan State
  middletennessee: { city: 'Murfreesboro', state: 'Tennessee', stateCode: 'TN' }, // Middle Tenn
  minnesota: { city: 'Minneapolis', state: 'Minnesota', stateCode: 'MN' }, // Minnesota
  mississippistate: { city: 'Starkville', state: 'Mississippi', stateCode: 'MS' }, // Mississippi St
  missouri: { city: 'Columbia', state: 'Missouri', stateCode: 'MO' }, // Missouri
  missouristate: { city: 'Springfield', state: 'Missouri', stateCode: 'MO' }, // Missouri State
  navy: { city: 'Annapolis', state: 'Maryland', stateCode: 'MD' }, // Navy
  ncstate: { city: 'Raleigh', state: 'North Carolina', stateCode: 'NC' }, // NC State
  nebraska: { city: 'Lincoln', state: 'Nebraska', stateCode: 'NE' }, // Nebraska
  nevada: { city: 'Reno', state: 'Nevada', stateCode: 'NV' }, // Nevada
  newmexico: { city: 'Albuquerque', state: 'New Mexico', stateCode: 'NM' }, // New Mexico
  newmexicostate: { city: 'Las Cruces', state: 'New Mexico', stateCode: 'NM' }, // New Mexico St.
  northcarolina: { city: 'Chapel Hill', state: 'North Carolina', stateCode: 'NC' }, // North Carolina
  northdakotastate: { city: 'Fargo', state: 'North Dakota', stateCode: 'ND' }, // NDSU
  northernillinois: { city: 'DeKalb', state: 'Illinois', stateCode: 'IL' }, // NIU
  northtexas: { city: 'Denton', state: 'Texas', stateCode: 'TX', metro: 'Dallas' }, // North Texas
  northwestern: { city: 'Evanston', state: 'Illinois', stateCode: 'IL', metro: 'Chicago' }, // Northwestern
  notredame: { city: 'Notre Dame', state: 'Indiana', stateCode: 'IN', metro: 'South Bend' }, // Notre Dame
  ohio: { city: 'Athens', state: 'Ohio', stateCode: 'OH' }, // Ohio
  ohiostate: { city: 'Columbus', state: 'Ohio', stateCode: 'OH' }, // Ohio State
  oklahoma: { city: 'Norman', state: 'Oklahoma', stateCode: 'OK' }, // Oklahoma
  oklahomastate: { city: 'Stillwater', state: 'Oklahoma', stateCode: 'OK' }, // Oklahoma State
  olddominion: { city: 'Norfolk', state: 'Virginia', stateCode: 'VA' }, // Old Dominion
  olemiss: { city: 'Oxford', state: 'Mississippi', stateCode: 'MS' }, // Ole Miss
  oregon: { city: 'Eugene', state: 'Oregon', stateCode: 'OR' }, // Oregon
  oregonstate: { city: 'Corvallis', state: 'Oregon', stateCode: 'OR' }, // Oregon State
  pennstate: { city: 'University Park', state: 'Pennsylvania', stateCode: 'PA', metro: 'State College' }, // Penn State
  pittsburgh: { city: 'Pittsburgh', state: 'Pennsylvania', stateCode: 'PA' }, // Pittsburgh
  purdue: { city: 'West Lafayette', state: 'Indiana', stateCode: 'IN', metro: 'Lafayette' }, // Purdue
  rice: { city: 'Houston', state: 'Texas', stateCode: 'TX' }, // Rice
  rutgers: { city: 'Piscataway', state: 'New Jersey', stateCode: 'NJ', metro: 'New Brunswick' }, // Rutgers
  sacramentostate: { city: 'Sacramento', state: 'California', stateCode: 'CA' }, // Sac State
  samhoustonstate: { city: 'Huntsville', state: 'Texas', stateCode: 'TX' }, // Sam Houston
  sandiegostate: { city: 'San Diego', state: 'California', stateCode: 'CA' }, // San Diego St.
  sanjosestate: { city: 'San Jose', state: 'California', stateCode: 'CA' }, // San Jose State
  smu: { city: 'University Park', state: 'Texas', stateCode: 'TX', metro: 'Dallas' }, // SMU
  southalabama: { city: 'Mobile', state: 'Alabama', stateCode: 'AL' }, // South Alabama
  southcarolina: { city: 'Columbia', state: 'South Carolina', stateCode: 'SC' }, // South Carolina
  southernmississippi: { city: 'Hattiesburg', state: 'Mississippi', stateCode: 'MS' }, // Southern Miss
  southflorida: { city: 'Tampa', state: 'Florida', stateCode: 'FL' }, // USF
  stanford: { city: 'Stanford', state: 'California', stateCode: 'CA', metro: 'Palo Alto' }, // Stanford
  syracuse: { city: 'Syracuse', state: 'New York', stateCode: 'NY' }, // Syracuse
  tcu: { city: 'Fort Worth', state: 'Texas', stateCode: 'TX' }, // TCU
  temple: { city: 'Philadelphia', state: 'Pennsylvania', stateCode: 'PA' }, // Temple
  tennessee: { city: 'Knoxville', state: 'Tennessee', stateCode: 'TN' }, // Tennessee
  texas: { city: 'Austin', state: 'Texas', stateCode: 'TX' }, // Texas
  texasam: { city: 'College Station', state: 'Texas', stateCode: 'TX' }, // Texas A&M
  texassanantonio: { city: 'San Antonio', state: 'Texas', stateCode: 'TX' }, // UTSA
  texasstate: { city: 'San Marcos', state: 'Texas', stateCode: 'TX' }, // Texas State
  texastech: { city: 'Lubbock', state: 'Texas', stateCode: 'TX' }, // Texas Tech
  toledo: { city: 'Toledo', state: 'Ohio', stateCode: 'OH' }, // Toledo
  troy: { city: 'Troy', state: 'Alabama', stateCode: 'AL' }, // Troy
  tulane: { city: 'New Orleans', state: 'Louisiana', stateCode: 'LA' }, // Tulane
  tulsa: { city: 'Tulsa', state: 'Oklahoma', stateCode: 'OK' }, // Tulsa
  uab: { city: 'Birmingham', state: 'Alabama', stateCode: 'AL' }, // UAB
  ucf: { city: 'Orlando', state: 'Florida', stateCode: 'FL' }, // UCF
  ucla: { city: 'Los Angeles', state: 'California', stateCode: 'CA' }, // UCLA
  unlv: { city: 'Las Vegas', state: 'Nevada', stateCode: 'NV' }, // UNLV
  usc: { city: 'Los Angeles', state: 'California', stateCode: 'CA' }, // USC
  utah: { city: 'Salt Lake City', state: 'Utah', stateCode: 'UT' }, // Utah
  utahstate: { city: 'Logan', state: 'Utah', stateCode: 'UT' }, // Utah State
  utep: { city: 'El Paso', state: 'Texas', stateCode: 'TX' }, // UTEP
  vanderbilt: { city: 'Nashville', state: 'Tennessee', stateCode: 'TN' }, // Vanderbilt
  virginia: { city: 'Charlottesville', state: 'Virginia', stateCode: 'VA' }, // Virginia
  virginiatech: { city: 'Blacksburg', state: 'Virginia', stateCode: 'VA' }, // Virginia Tech
  wakeforest: { city: 'Winston-Salem', state: 'North Carolina', stateCode: 'NC' }, // Wake Forest
  washington: { city: 'Seattle', state: 'Washington', stateCode: 'WA' }, // Washington
  washingtonstate: { city: 'Pullman', state: 'Washington', stateCode: 'WA' }, // Washington St.
  westernkentucky: { city: 'Bowling Green', state: 'Kentucky', stateCode: 'KY' }, // W. Kentucky
  westernmichigan: { city: 'Kalamazoo', state: 'Michigan', stateCode: 'MI' }, // W. Michigan
  westvirginia: { city: 'Morgantown', state: 'West Virginia', stateCode: 'WV' }, // West Virginia
  wisconsin: { city: 'Madison', state: 'Wisconsin', stateCode: 'WI' }, // Wisconsin
  wyoming: { city: 'Laramie', state: 'Wyoming', stateCode: 'WY' }, // Wyoming
};

/**
 * Where a school is, or undefined if it isn't one we know.
 *
 * Undefined is a real answer: a TeamBuilder import or roster mod can carry a
 * name that was never in EA's list, and inventing a location for it would be
 * worse than showing nothing.
 */
export function schoolLocation(teamName: string | null | undefined): SchoolLocation | undefined {
  if (!teamName) return undefined;
  return SCHOOL_LOCATIONS[canonicalKey(teamName)];
}

/**
 * "Los Angeles, CA" — the masthead label. Null when unknown, so a caller
 * renders nothing rather than a stray comma.
 *
 * `preferMetro` swaps in the recognisable city; leave it off for anything
 * factual (this school is in Chestnut Hill) and turn it on for anything
 * pictorial (this is a picture of Boston).
 */
export function schoolLocationLabel(
  teamName: string | null | undefined,
  opts?: { full?: boolean; preferMetro?: boolean },
): string | null {
  const found = schoolLocation(teamName);
  if (!found) return null;
  const place = opts?.preferMetro ? (found.metro ?? found.city) : found.city;
  return `${place}, ${opts?.full ? found.state : found.stateCode}`;
}

/**
 * Extra words a team dropdown should match on, beyond the display name.
 *
 * EA abbreviates: "App St.", "Jax State", "C. Michigan", "Middle Tenn". Someone
 * searching a 138-row dropdown types the name they know, which is usually the
 * long one — so without this, "Appalachian" finds nothing. The city is included
 * too, since "Boone" or "Ann Arbor" is how some people think of a program.
 *
 * Kept here rather than hand-written per call site because this module already
 * holds the one authoritative city per school, and `canonicalKey` already
 * resolves the abbreviations — so both halves are data the app maintains anyway.
 */
export function expandTeamSearchTerms(teamName: string): string {
  const found = schoolLocation(teamName);
  const words = [
    teamName.replace(/\bSt\.\b/g, 'State'),
    teamName.replace(/^C\.\s/, 'Central ').replace(/^E\.\s/, 'Eastern ').replace(/^W\.\s/, 'Western ').replace(/^N\.\s/, 'Northern ').replace(/^S\.\s/, 'Southern '),
    found?.city ?? '',
    found?.metro ?? '',
    found?.state ?? '',
  ];
  return [...new Set(words.filter(Boolean))].join(' ');
}
