export const IPC = {
  fs: {
    selectFile: 'fs:selectFile',
    getDefaultSavesDir: 'fs:getDefaultSavesDir',
    scanForSaves: 'fs:scanForSaves',
  },
  assets: {
    getStatus: 'assets:getStatus',
    chooseFolder: 'assets:chooseFolder',
    clearPath: 'assets:clearPath',
  },
  db: {
    getDynasties: 'db:getDynasties',
    importDynasty: 'db:importDynasty',
    checkDynastyMatch: 'db:checkDynastyMatch',
    relinkDynasty: 'db:relinkDynasty',
    syncDynasty: 'db:syncDynasty',
    getSeasonOverview: 'db:getSeasonOverview',
    getNcaaHub: 'db:getNcaaHub',
    getHistory: 'db:getHistory',
    deleteDynasty: 'db:deleteDynasty',
    getSeasons: 'db:getSeasons',
    getRoster: 'db:getRoster',
    getPlayerStats: 'db:getPlayerStats',
    getTeamStats: 'db:getTeamStats',
    getTeamGameStats: 'db:getTeamGameStats',
    getTeamCard: 'db:getTeamCard',
    getNationalTeamStats: 'db:getNationalTeamStats',
    getNationalStatLeaders: 'db:getNationalStatLeaders',
    getKickingStats: 'db:getKickingStats',
    getGameLog: 'db:getGameLog',
    getGameDetail: 'db:getGameDetail',
    getTeamTrophies: 'db:getTeamTrophies',
    getSchedule: 'db:getSchedule',
    getStandings: 'db:getStandings',
    getCoaches: 'db:getCoaches',
    getAwards: 'db:getAwards',
    getRankings: 'db:getRankings',
    getRecruits: 'db:getRecruits',
    getLeagueTeams: 'db:getLeagueTeams',
    getLeagueScores: 'db:getLeagueScores',
    getLeagueTeamOverview: 'db:getLeagueTeamOverview',
    getLeagueTeamRoster: 'db:getLeagueTeamRoster',
    getAllLeaguePlayers: 'db:getAllLeaguePlayers',
    getLeagueTeamSchedule: 'db:getLeagueTeamSchedule',
    getLeagueTeamHonors: 'db:getLeagueTeamHonors',
    getNationalRecruits: 'db:getNationalRecruits',
    getNcaaRecords: 'db:getNcaaRecords',
    getDynastyTrends: 'db:getDynastyTrends',
    getTransfers: 'db:getTransfers',
    getDepartures: 'db:getDepartures',
    globalSearch: 'db:globalSearch',
    getPlayerDevelopment: 'db:getPlayerDevelopment',
    getHeadToHead: 'db:getHeadToHead',
    getCoachingTree: 'db:getCoachingTree',
    getDynastyTheme: 'db:getDynastyTheme',
    getSeasonTheme: 'db:getSeasonTheme',
    getTeamAwardDefinitions: 'db:getTeamAwardDefinitions',
    getTeamAwardResults: 'db:getTeamAwardResults',
    calculateTeamAward: 'db:calculateTeamAward',
    confirmTeamAwardWinner: 'db:confirmTeamAwardWinner',
    selectManualAwardWinner: 'db:selectManualAwardWinner',
    finalizeTeamAwards: 'db:finalizeTeamAwards',
    unlockTeamAwards: 'db:unlockTeamAwards',
    getTeamAwardSettings: 'db:getTeamAwardSettings',
    saveTeamAwardSettings: 'db:saveTeamAwardSettings',
    getTeamAwardHistory: 'db:getTeamAwardHistory',
  },
  extraction: {
    extractAll: 'extract:all',
    progress: 'extract:progress',
  },
  export: {
    historyToHtml: 'export:historyToHtml',
    seasonYearbookToHtml: 'export:seasonYearbookToHtml',
  },
  editor: {
    backupSaveFile: 'editor:backupSaveFile',
    getPlayer: 'editor:getPlayer',
    savePlayer: 'editor:savePlayer',
    getCoach: 'editor:getCoach',
    saveCoach: 'editor:saveCoach',
    getRecruit: 'editor:getRecruit',
    saveRecruit: 'editor:saveRecruit',
    saveRecruitInfluence: 'editor:saveRecruitInfluence',
    getTeamBudget: 'editor:getTeamBudget',
    saveTeamBudget: 'editor:saveTeamBudget',
    forceCommitRecruit: 'editor:forceCommitRecruit',
    searchPortraits: 'editor:searchPortraits',
  },
  media: {
    pickFiles: 'media:pickFiles',
    addFiles: 'media:addFiles',
    list: 'media:list',
    listForPlayer: 'media:listForPlayer',
    listForGame: 'media:listForGame',
    update: 'media:update',
    remove: 'media:remove',
  },
  notes: {
    list: 'notes:list',
    create: 'notes:create',
    update: 'notes:update',
    remove: 'notes:remove',
    titleSuggestions: 'notes:titleSuggestions',
  },
  update: {
    check: 'update:check',
    openDownload: 'update:openDownload',
  },
} as const;
