export const IPC = {
  fs: {
    selectFile: 'fs:selectFile',
    getDefaultSavesDir: 'fs:getDefaultSavesDir',
    scanForSaves: 'fs:scanForSaves',
    peekSave: 'fs:peekSave',
    chooseSavesFolder: 'fs:chooseSavesFolder',
  },
  assets: {
    getStatus: 'assets:getStatus',
    chooseFolder: 'assets:chooseFolder',
    clearPath: 'assets:clearPath',
  },
  db: {
    getDynasties: 'db:getDynasties',
    importDynasty: 'db:importDynasty',
    checkDynastyMatch: 'db:checkDynastyMatch',
    relinkDynasty: 'db:relinkDynasty',
    syncDynasty: 'db:syncDynasty',
    getSeasonOverview: 'db:getSeasonOverview',
    getNcaaHub: 'db:getNcaaHub',
    getHistory: 'db:getHistory',
    deleteDynasty: 'db:deleteDynasty',
    getSeasons: 'db:getSeasons',
    getRoster: 'db:getRoster',
    getPlayerStats: 'db:getPlayerStats',
    getTeamStats: 'db:getTeamStats',
    getTeamGameStats: 'db:getTeamGameStats',
    getTeamCard: 'db:getTeamCard',
    getNationalTeamStats: 'db:getNationalTeamStats',
    getNationalStatLeaders: 'db:getNationalStatLeaders',
    getKickingStats: 'db:getKickingStats',
    getGameLog: 'db:getGameLog',
    getPlayerGameLog: 'db:getPlayerGameLog',
    getGameDetail: 'db:getGameDetail',
    getTeamTrophies: 'db:getTeamTrophies',
    getSchedule: 'db:getSchedule',
    getStandings: 'db:getStandings',
    getCoaches: 'db:getCoaches',
    getAwards: 'db:getAwards',
    getRankings: 'db:getRankings',
    getRecruits: 'db:getRecruits',
    getLeagueTeams: 'db:getLeagueTeams',
    getLeagueScores: 'db:getLeagueScores',
    getLeagueTeamOverview: 'db:getLeagueTeamOverview',
    getLeagueTeamRoster: 'db:getLeagueTeamRoster',
    getAllLeaguePlayers: 'db:getAllLeaguePlayers',
    getLeagueTeamSchedule: 'db:getLeagueTeamSchedule',
    getLeagueTeamHonors: 'db:getLeagueTeamHonors',
    getNationalRecruits: 'db:getNationalRecruits',
    getRecruitById: 'db:getRecruitById',
    getTeamHistory: 'db:getTeamHistory',
    getNcaaRecords: 'db:getNcaaRecords',
    getDynastyTrends: 'db:getDynastyTrends',
    getSeasonAnalytics: 'db:getSeasonAnalytics',
    getProgramArc: 'db:getProgramArc',
    getTransfers: 'db:getTransfers',
    getDepartures: 'db:getDepartures',
    globalSearch: 'db:globalSearch',
    getPlayerDevelopment: 'db:getPlayerDevelopment',
    getHeadToHead: 'db:getHeadToHead',
    getCoachingTree: 'db:getCoachingTree',
    getDynastyTheme: 'db:getDynastyTheme',
    getTeamTheme: 'db:getTeamTheme',
    getSeasonTheme: 'db:getSeasonTheme',
    getTeamAwardDefinitions: 'db:getTeamAwardDefinitions',
    getTeamAwardResults: 'db:getTeamAwardResults',
    calculateTeamAward: 'db:calculateTeamAward',
    confirmTeamAwardWinner: 'db:confirmTeamAwardWinner',
    selectManualAwardWinner: 'db:selectManualAwardWinner',
    finalizeTeamAwards: 'db:finalizeTeamAwards',
    unlockTeamAwards: 'db:unlockTeamAwards',
    getTeamAwardSettings: 'db:getTeamAwardSettings',
    saveTeamAwardSettings: 'db:saveTeamAwardSettings',
    getTeamAwardHistory: 'db:getTeamAwardHistory',
  },
  extraction: {
    extractAll: 'extract:all',
    progress: 'extract:progress',
  },
  export: {
    historyToHtml: 'export:historyToHtml',
    seasonYearbookToHtml: 'export:seasonYearbookToHtml',
    playerCardToPng: 'export:playerCardToPng',
    pickCardFolder: 'export:pickCardFolder',
    playerCardToFolder: 'export:playerCardToFolder',
  },
  editor: {
    backupSaveFile: 'editor:backupSaveFile',
    getScandals: 'editor:getScandals',
    saveScandals: 'editor:saveScandals',
    estimateDynastyBackup: 'editor:estimateDynastyBackup',
    createDynastyBackup: 'editor:createDynastyBackup',
    backupProgress: 'editor:backupProgress',
    chooseBackupToRestore: 'editor:chooseBackupToRestore',
    restoreDynastyBackup: 'editor:restoreDynastyBackup',
    getPlayer: 'editor:getPlayer',
    savePlayer: 'editor:savePlayer',
    getCoach: 'editor:getCoach',
    saveCoach: 'editor:saveCoach',
    getRecruit: 'editor:getRecruit',
    saveRecruit: 'editor:saveRecruit',
    saveRecruitInfluence: 'editor:saveRecruitInfluence',
    getTeamBudget: 'editor:getTeamBudget',
    saveTeamBudget: 'editor:saveTeamBudget',
    forceCommitRecruit: 'editor:forceCommitRecruit',
    searchPortraits: 'editor:searchPortraits',
  },
  card: {
    // Photo files. The legacy four are keyed by player (one photo per player) and
    // stay because cards made before schema v12 adopt those files where they sit;
    // the *ForCard trio is keyed by card, which is what multiple cards needs.
    pickPhoto: 'card:pickPhoto',
    setPhotoFromPath: 'card:setPhotoFromPath',
    getPhoto: 'card:getPhoto',
    removePhoto: 'card:removePhoto',
    pickPhotoForCard: 'card:pickPhotoForCard',
    setCardPhotoFromPath: 'card:setCardPhotoFromPath',
    removeCardPhoto: 'card:removeCardPhoto',
    // Saved cards (schema v12).
    list: 'card:list',
    listFavorites: 'card:listFavorites',
    listCardedPlayerIds: 'card:listCardedPlayerIds',
    create: 'card:create',
    update: 'card:update',
    setFavorite: 'card:setFavorite',
    setDefault: 'card:setDefault',
    remove: 'card:remove',
  },
  program: {
    list: 'program:list',
    setIdentity: 'program:setIdentity',
    pickArt: 'program:pickArt',
    clearArt: 'program:clearArt',
  },
  media: {
    pickFiles: 'media:pickFiles',
    addFiles: 'media:addFiles',
    list: 'media:list',
    listForPlayer: 'media:listForPlayer',
    listForGame: 'media:listForGame',
    update: 'media:update',
    setFraming: 'media:setFraming',
    reorder: 'media:reorder',
    remove: 'media:remove',
    getStorageUsage: 'media:getStorageUsage',
    cleanUpBackups: 'media:cleanUpBackups',
    clearDeletedDynastyCache: 'media:clearDeletedDynastyCache',
    getLibraryStatus: 'media:getLibraryStatus',
    chooseLibraryFolder: 'media:chooseLibraryFolder',
    resetLibraryFolder: 'media:resetLibraryFolder',
    openLibraryFolder: 'media:openLibraryFolder',
  },
  notes: {
    list: 'notes:list',
    create: 'notes:create',
    update: 'notes:update',
    remove: 'notes:remove',
    titleSuggestions: 'notes:titleSuggestions',
  },
  update: {
    check: 'update:check',
    openDownload: 'update:openDownload',
  },
  window: {
    /** Recolours the Windows Control Overlay strip when the app's light/dark appearance flips. */
    setTitleBarTheme: 'window:setTitleBarTheme',
  },
} as const;
