export const IPC = {
  fs: {
    selectFile: 'fs:selectFile',
    getDefaultSavesDir: 'fs:getDefaultSavesDir',
    scanForSaves: 'fs:scanForSaves',
  },
  db: {
    getDynasties: 'db:getDynasties',
    importDynasty: 'db:importDynasty',
    checkDynastyMatch: 'db:checkDynastyMatch',
    relinkDynasty: 'db:relinkDynasty',
    syncDynasty: 'db:syncDynasty',
    getSeasonOverview: 'db:getSeasonOverview',
    getNcaaHub: 'db:getNcaaHub',
    getHistory: 'db:getHistory',
    deleteDynasty: 'db:deleteDynasty',
    getSeasons: 'db:getSeasons',
    getRoster: 'db:getRoster',
    getPlayerStats: 'db:getPlayerStats',
    getTeamStats: 'db:getTeamStats',
    getKickingStats: 'db:getKickingStats',
    getGameLog: 'db:getGameLog',
    getTeamTrophies: 'db:getTeamTrophies',
    getSchedule: 'db:getSchedule',
    getStandings: 'db:getStandings',
    getCoaches: 'db:getCoaches',
    getAwards: 'db:getAwards',
    getRankings: 'db:getRankings',
    getRecruits: 'db:getRecruits',
    getLeagueTeams: 'db:getLeagueTeams',
    getLeagueTeamRoster: 'db:getLeagueTeamRoster',
    getDynastyTheme: 'db:getDynastyTheme',
    getTeamAwardDefinitions: 'db:getTeamAwardDefinitions',
    getTeamAwardResults: 'db:getTeamAwardResults',
    calculateTeamAward: 'db:calculateTeamAward',
    confirmTeamAwardWinner: 'db:confirmTeamAwardWinner',
    selectManualAwardWinner: 'db:selectManualAwardWinner',
    finalizeTeamAwards: 'db:finalizeTeamAwards',
    unlockTeamAwards: 'db:unlockTeamAwards',
    getTeamAwardSettings: 'db:getTeamAwardSettings',
    saveTeamAwardSettings: 'db:saveTeamAwardSettings',
    getTeamAwardHistory: 'db:getTeamAwardHistory',
  },
  extraction: {
    extractAll: 'extract:all',
    progress: 'extract:progress',
  },
  export: {
    historyToHtml: 'export:historyToHtml',
  },
  editor: {
    backupSaveFile: 'editor:backupSaveFile',
    getPlayer: 'editor:getPlayer',
    savePlayer: 'editor:savePlayer',
    getCoach: 'editor:getCoach',
    saveCoach: 'editor:saveCoach',
    getRecruit: 'editor:getRecruit',
    saveRecruit: 'editor:saveRecruit',
    searchPortraits: 'editor:searchPortraits',
  },
} as const;
